package com.minhafazendinha.game

import android.content.Context
import android.graphics.*
import android.util.AttributeSet
import android.view.MotionEvent
import android.view.View
import kotlin.math.sin

class Cow3DView @JvmOverloads constructor(context:Context,attrs:AttributeSet?=null):View(context,attrs){
 private val p=Paint(Paint.ANTI_ALIAS_FLAG);private var angle=-.25f;private var lastX=0f;private var accessory="";private var careState=0;private var pilotVisual=false
 fun setAccessory(v:String){accessory=v.trim();invalidate()}
 fun setCareState(state:Int){careState=state.coerceIn(0,3);invalidate()}
 fun setPilotVisual(enabled:Boolean){pilotVisual=enabled;invalidate()}
 override fun onDraw(c:Canvas){super.onDraw(c);val w=width.toFloat();val h=height.toFloat();val s=minOf(w,h)*if(pilotVisual).235f else .22f;val cx=w*.49f;val cy=h*.58f
  if(pilotVisual)drawPilotBackground(c,w,h,s) else drawClassicBackground(c,w,h,s)
  p.color=0x26000000;c.drawOval(cx-s*1.65f,cy+s*.72f,cx+s*1.55f,cy+s*1.12f,p)
  val turn=sin(angle);val shift=turn*s*.13f;p.color=0xFFF7F4E9.toInt();c.drawOval(cx-s*1.28f+shift,cy-s*.55f,cx+s*.92f+shift,cy+s*.62f,p);p.color=0xFF242424.toInt();c.drawOval(cx-s*.9f+shift,cy-s*.42f,cx-s*.32f+shift,cy+s*.08f,p);c.drawOval(cx-s*.12f+shift,cy+s*.04f,cx+s*.48f+shift,cy+s*.48f,p);c.drawOval(cx+s*.35f+shift,cy-s*.42f,cx+s*.72f+shift,cy-s*.08f,p)
  for(dx in floatArrayOf(-.78f,-.38f,.35f,.68f)){p.color=0xFFF3F0E6.toInt();c.drawRoundRect(cx+s*dx-s*.11f,cy+s*.42f,cx+s*dx+s*.11f,cy+s*1.03f,s*.1f,s*.1f,p);p.color=0xFF343434.toInt();c.drawRoundRect(cx+s*dx-s*.13f,cy+s*.91f,cx+s*dx+s*.13f,cy+s*1.08f,s*.08f,s*.08f,p)}
  val hx=cx+s*(.91f+turn*.12f);val hy=cy-s*.35f;p.color=0xFFFFFCF2.toInt();c.drawOval(hx-s*.55f,hy-s*.62f,hx+s*.55f,hy+s*.48f,p);p.color=0xFF7D5539.toInt();c.drawOval(hx-s*.72f,hy-s*.42f,hx-s*.38f,hy-s*.18f,p);c.drawOval(hx+s*.38f,hy-s*.42f,hx+s*.72f,hy-s*.18f,p);p.color=0xFFFFD78A.toInt();c.drawOval(hx-s*.4f,hy-s*.72f,hx-s*.2f,hy-s*.43f,p);c.drawOval(hx+s*.2f,hy-s*.72f,hx+s*.4f,hy-s*.43f,p)
  p.color=Color.WHITE;c.drawCircle(hx-s*.2f,hy-s*.18f,s*.14f,p);c.drawCircle(hx+s*.2f,hy-s*.18f,s*.14f,p);p.color=0xFF242424.toInt();if(careState==3){p.strokeWidth=s*.035f;c.drawLine(hx-s*.3f,hy-s*.16f,hx-s*.1f,hy-s*.16f,p);c.drawLine(hx+s*.1f,hy-s*.16f,hx+s*.3f,hy-s*.16f,p)}else{c.drawCircle(hx-s*.18f,hy-s*.16f,s*.065f,p);c.drawCircle(hx+s*.18f,hy-s*.16f,s*.065f,p);p.color=Color.WHITE;c.drawCircle(hx-s*.155f,hy-s*.19f,s*.022f,p);c.drawCircle(hx+s*.205f,hy-s*.19f,s*.022f,p)}
  p.color=0xFFFFB5C5.toInt();c.drawOval(hx-s*.42f,hy+s*.05f,hx+s*.42f,hy+s*.42f,p);p.color=0xFFD87F98.toInt();c.drawCircle(hx-s*.18f,hy+s*.23f,s*.045f,p);c.drawCircle(hx+s*.18f,hy+s*.23f,s*.045f,p)
  p.style=Paint.Style.STROKE;p.strokeCap=Paint.Cap.ROUND;p.strokeWidth=s*.055f;p.color=0xFF3B302A.toInt();val tail=Path();tail.moveTo(cx-s*1.2f,cy-s*.05f);tail.cubicTo(cx-s*1.62f,cy-s*.3f,cx-s*1.55f,cy+s*.3f,cx-s*1.72f,cy+s*.25f);c.drawPath(tail,p);p.style=Paint.Style.FILL;c.drawCircle(cx-s*1.72f,cy+s*.25f,s*.1f,p)
  when(careState){0->{p.textSize=s*.35f;p.textAlign=Paint.Align.CENTER;c.drawText("🍎",cx-s*.15f,cy+s*1.42f,p)};1->{p.color=0xFF65C9F3.toInt();for(i in 0..7)c.drawCircle(cx+s*((i%4)*.42f-.7f),cy+s*((i/4)*.35f-.35f),s*.12f,p);p.color=Color.WHITE;for(i in 0..5)c.drawCircle(cx+s*((i%3)*.45f-.45f),cy+s*((i/3)*.35f-.2f),s*.14f,p)};2->{p.textSize=s*.32f;p.textAlign=Paint.Align.CENTER;c.drawText("✨  ✨",cx,cy-s*.75f,p)};3->{p.textSize=s*.32f;p.textAlign=Paint.Align.CENTER;c.drawText("💤  Zzz",cx+s*.7f,cy-s*1.0f,p)}}
  accessory(c,hx,hy-s*.72f,s);p.color=if(careState==3)Color.WHITE else if(pilotVisual)VisualPilot.ink else 0xFF4B7B38.toInt();p.textSize=s*.16f;p.textAlign=Paint.Align.CENTER;c.drawText(if(pilotVisual)"↔ gire a Mimosa" else "↔ arraste para girar",cx,h*.96f,p)
 }
 private fun drawClassicBackground(c:Canvas,w:Float,h:Float,s:Float){c.drawColor(if(careState==3)Color.rgb(72,93,145) else Color.rgb(166,224,255));if(careState!=3){p.color=0xFFFFE36E.toInt();c.drawCircle(w*.84f,h*.14f,s*.25f,p)}else{p.color=0xFFFFF3B0.toInt();c.drawCircle(w*.84f,h*.14f,s*.23f,p);p.color=0xFF485D91.toInt();c.drawCircle(w*.9f,h*.1f,s*.23f,p)};p.color=Color.WHITE;cloud(c,w*.16f,h*.16f,s);if(careState!=3)cloud(c,w*.7f,h*.25f,s*.72f);p.color=if(careState==3)0xFF467047.toInt() else 0xFF76C95A.toInt();c.drawRect(0f,h*.66f,w,h,p);p.color=if(careState==3)0xFF3C623E.toInt() else 0xFF5FA947.toInt();c.drawOval(-w*.1f,h*.6f,w*.6f,h*.82f,p);c.drawOval(w*.42f,h*.61f,w*1.1f,h*.82f,p);barn(c,w*.08f,h*.39f,s);fence(c,w,h,s)}
 private fun drawPilotBackground(c:Canvas,w:Float,h:Float,s:Float){val bg=LinearGradient(0f,0f,0f,h*.7f,VisualPilot.skyTop,VisualPilot.skyBottom,Shader.TileMode.CLAMP);p.shader=bg;c.drawRect(0f,0f,w,h*.72f,p);p.shader=null;p.color=0xFFFFDF72.toInt();c.drawCircle(w*.83f,h*.13f,s*.24f,p);p.color=0x44FFFFFF;c.drawCircle(w*.83f,h*.13f,s*.34f,p);p.color=Color.WHITE;cloud(c,w*.16f,h*.15f,s*.82f);cloud(c,w*.62f,h*.24f,s*.58f);p.color=VisualPilot.grassLight;c.drawRect(0f,h*.64f,w,h,p);p.color=VisualPilot.grassDark;c.drawOval(-w*.18f,h*.57f,w*.58f,h*.82f,p);c.drawOval(w*.38f,h*.59f,w*1.15f,h*.84f,p);barn(c,w*.07f,h*.36f,s);fence(c,w,h,s);p.color=0x66FFFFFF;c.drawRoundRect(w*.04f,h*.04f,w*.96f,h*.94f,VisualPilot.sceneRadius,VisualPilot.sceneRadius,p);p.style=Paint.Style.STROKE;p.strokeWidth=5f;p.color=0x55FFFFFF;c.drawRoundRect(w*.04f,h*.04f,w*.96f,h*.94f,VisualPilot.sceneRadius,VisualPilot.sceneRadius,p);p.style=Paint.Style.FILL}
 private fun cloud(c:Canvas,x:Float,y:Float,s:Float){p.color=Color.WHITE;c.drawCircle(x-s*.22f,y,s*.2f,p);c.drawCircle(x,y-s*.08f,s*.28f,p);c.drawCircle(x+s*.25f,y,s*.19f,p);c.drawOval(x-s*.38f,y,x+s*.42f,y+s*.2f,p)}
 private fun barn(c:Canvas,x:Float,y:Float,s:Float){p.color=0xFFD85845.toInt();c.drawRect(x,y,x+s*.95f,y+s*.7f,p);val r=Path();r.moveTo(x-s*.12f,y);r.lineTo(x+s*.48f,y-s*.42f);r.lineTo(x+s*1.08f,y);r.close();p.color=0xFF8D3C32.toInt();c.drawPath(r,p);p.color=0xFFF8E7C4.toInt();c.drawRect(x+s*.32f,y+s*.28f,x+s*.65f,y+s*.7f,p)}
 private fun fence(c:Canvas,w:Float,h:Float,s:Float){p.color=if(pilotVisual)VisualPilot.wood else 0xFFF4D29B.toInt();for(x in listOf(w*.03f,w*.26f,w*.74f,w*.94f))c.drawRoundRect(x,h*.58f,x+s*.1f,h*.8f,s*.03f,s*.03f,p);c.drawRect(0f,h*.66f,w,h*.7f,p);c.drawRect(0f,h*.75f,w,h*.79f,p)}
 private fun accessory(c:Canvas,x:Float,y:Float,s:Float){when(accessory){"👒","🧢","🎩"->{p.color=if(accessory=="🧢")0xFF4285F4.toInt()else if(accessory=="🎩")0xFF292929.toInt()else 0xFFFFD45C.toInt();c.drawOval(x-s*.52f,y-s*.05f,x+s*.52f,y+s*.12f,p);c.drawRoundRect(x-s*.3f,y-s*.38f,x+s*.3f,y+s*.03f,s*.1f,s*.1f,p)};"👑"->{p.color=0xFFFFC928.toInt();val q=Path();q.moveTo(x-s*.42f,y+s*.08f);q.lineTo(x-s*.36f,y-s*.35f);q.lineTo(x-s*.12f,y-s*.12f);q.lineTo(x,y-s*.46f);q.lineTo(x+s*.14f,y-s*.12f);q.lineTo(x+s*.38f,y-s*.35f);q.lineTo(x+s*.42f,y+s*.08f);q.close();c.drawPath(q,p)};"🎀"->{p.color=0xFFFF5B91.toInt();c.drawCircle(x-s*.18f,y,s*.21f,p);c.drawCircle(x+s*.18f,y,s*.21f,p);p.color=0xFFFF9BBA.toInt();c.drawCircle(x,y,s*.11f,p)};"🕶️"->{p.style=Paint.Style.STROKE;p.strokeWidth=s*.09f;p.color=Color.BLACK;c.drawCircle(x-s*.2f,y+s*.65f,s*.17f,p);c.drawCircle(x+s*.2f,y+s*.65f,s*.17f,p);c.drawLine(x-s*.03f,y+s*.65f,x+s*.03f,y+s*.65f,p);p.style=Paint.Style.FILL};"🧣"->{p.color=0xFFE84D4D.toInt();c.drawRoundRect(x-s*.4f,y+s*1.12f,x+s*.4f,y+s*1.3f,s*.08f,s*.08f,p)}}}
 override fun onTouchEvent(e:MotionEvent):Boolean{when(e.actionMasked){MotionEvent.ACTION_DOWN->lastX=e.x;MotionEvent.ACTION_MOVE->{angle=(angle+(e.x-lastX)/230f).coerceIn(-1.1f,1.1f);lastX=e.x;invalidate()};MotionEvent.ACTION_UP,MotionEvent.ACTION_CANCEL->performClick()};return true}
 override fun performClick():Boolean{super.performClick();return true}
}