package com.minhafazendinha.game

/**
 * Portable handoff generated by the reusable game factory.
 *
 * The manifest is intentionally Android/UI agnostic: future games can use it to drive
 * art production, QA and release tooling without duplicating gameplay code.
 */
data class GameFactoryManifest(
    val gameId: String,
    val title: String,
    val characterId: String,
    val visualPack: String,
    val soundPack: String,
    val actions: List<String>,
    val visualAssets: List<String>,
    val soundAssets: List<String>,
    val issues: List<String>
) {
    val isReady: Boolean get() = issues.isEmpty()
    val assetCount: Int get() = visualAssets.size + soundAssets.size

    /** Stable text representation useful in CI logs and artist handoff documents. */
    fun summary(): String = buildString {
        append(gameId)
        append(" | character=")
        append(characterId)
        append(" | actions=")
        append(actions.joinToString(","))
        append(" | assets=")
        append(assetCount)
        append(" | ready=")
        append(isReady)
        if (issues.isNotEmpty()) {
            append(" | issues=")
            append(issues.joinToString(","))
        }
    }
}

/**
 * One entry point for bootstrapping the content pipeline of the next care game.
 * Keeping naming rules here prevents each game from inventing its own asset layout.
 */
object GameFactoryManifestBuilder {
    fun build(template: GameTemplate): GameFactoryManifest {
        val plan = GameLaunchPlanner.plan(template)
        return GameFactoryManifest(
            gameId = template.id,
            title = template.title,
            characterId = template.characterId,
            visualPack = template.visualPack,
            soundPack = template.soundPack,
            actions = template.primaryLoop.map { it.key },
            visualAssets = plan.requiredVisuals.sorted(),
            soundAssets = plan.requiredSounds.sorted(),
            issues = plan.issues.distinct().sorted()
        )
    }

    /**
     * Produces deterministic suggested resource names for art/audio still to be created.
     * Existing runtime keys remain untouched; this is a production convention only.
     */
    fun suggestedAssetNames(template: GameTemplate): List<String> = buildList {
        val prefix = sanitize(template.id)
        add("${prefix}_scene")
        add("${prefix}_${sanitize(template.characterId)}_idle")
        template.primaryLoop.forEach { action ->
            add("${prefix}_${sanitize(template.characterId)}_${action.key}")
            add("${prefix}_sfx_${action.key}")
        }
    }.distinct()

    /** Batch preflight makes adding several future games cheap and consistent. */
    fun buildAll(templates: Iterable<GameTemplate>): List<GameFactoryManifest> =
        templates.map(::build)

    private fun sanitize(value: String): String = value
        .trim()
        .lowercase()
        .map { if (it.isLetterOrDigit()) it else '_' }
        .joinToString("")
        .replace(Regex("_+"), "_")
        .trim('_')

    val farm: GameFactoryManifest by lazy { build(GameTemplateFactory.farm) }
}
