package com.minhafazendinha.game

import android.os.Bundle
import android.view.Gravity
import android.view.View
import android.widget.*
import androidx.appcompat.app.AppCompatActivity

class MainActivity:AppCompatActivity(){
 private lateinit var soundPlayer:AnimalSoundPlayer;private lateinit var stage2d:AnimalStageView;private lateinit var cow3d:Cow3DView;private lateinit var status:TextView
 private var selectedAnimal="vaca";private var selectedEmoji="🐮";private val prefs by lazy{getSharedPreferences("farm_progress",MODE_PRIVATE)}
 private val animals=listOf(Triple("🐮","Vaca","vaca"),Triple("🐔","Galinha","galinha"),Triple("🐶","Cachorro","cachorro"),Triple("🐴","Cavalo","cavalo"),Triple("🐷","Porco","porco"),Triple("🐑","Ovelha","ovelha"),Triple("🐐","Cabra","cabra"),Triple("🫏","Burro","burro"))
 private var stars:Int get()=prefs.getInt("stars",0);set(v){prefs.edit().putInt("stars",v).apply()};private var hearts:Int get()=prefs.getInt("hearts",0);set(v){prefs.edit().putInt("hearts",v).apply()}
 override fun onCreate(b:Bundle?){super.onCreate(b);soundPlayer=AnimalSoundPlayer(this);showHome()}
 private fun base(title:String,sub:String)=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;gravity=Gravity.CENTER_HORIZONTAL;setPadding(28,30,28,36);setBackgroundColor(0xFFEAF7D5.toInt());addView(TextView(this@MainActivity).apply{text="⭐ $stars     ❤️ $hearts";textSize=18f;gravity=Gravity.END});addView(TextView(this@MainActivity).apply{text=title;textSize=28f;gravity=Gravity.CENTER});addView(TextView(this@MainActivity).apply{text=sub;textSize=16f;gravity=Gravity.CENTER;setPadding(0,8,0,18)})}
 private fun btn(t:String,click:()->Unit)=Button(this).apply{text=t;textSize=19f;isAllCaps=false;setOnClickListener{click()}};private fun p()=LinearLayout.LayoutParams(-1,-2).apply{setMargins(0,8,0,8)};private fun set(c:LinearLayout)=setContentView(ScrollView(this).apply{addView(c)})
 private fun showHome(){val lake=stars>=15;val c=base("🌻 MINHA FAZENDINHA","Cuide, plante e descubra os bichinhos!");c.addView(TextView(this).apply{text="☀️   ☁️      ☁️\n🌳   🏡   🌳\n🐮  🌾  🐔\n🌻🌻🌻🌻🌻";textSize=42f;gravity=Gravity.CENTER;setPadding(0,12,0,22)});c.addView(btn("🔊 SONS DOS BICHINHOS"){showSounds()},p());c.addView(btn("🐮 CURRAL — Cuidar"){showCare(0)},p());c.addView(btn("🌱 HORTA — Plantar e colher"){showFarm(0)},p());c.addView(btn("🐔 GALINHEIRO — Pegar ovos"){showFarm(2)},p());c.addView(btn("👕 ARMÁRIO — Animais e roupas"){showLab()},p());c.addView(btn(if(lake)"🦆 LAGO — Liberado!" else "🔒 LAGO — Libera com 15 ⭐"){if(lake)showLake()},p());set(c)}
 private fun showSounds(){val c=base("🔊 SONS DOS BICHINHOS","Toque no bichinho para ouvir!");c.addView(TextView(this).apply{text="👶 🎵 🐾";textSize=40f;gravity=Gravity.CENTER;setPadding(0,5,0,18)});animals.forEach{(e,n,k)->c.addView(btn("$e     $n     🔊"){soundPlayer.playExtended(k)}.apply{textSize=29f;minHeight=110},p())};c.addView(btn("🏠 Voltar ao mapa"){showHome()},p());set(c)}
 private fun showCare(step:Int){val s=listOf("🍎 Alimentar" to "Dê comida para a vaquinha","🛁 Banho" to "Deixe a vaquinha limpinha","🧻 Secar" to "Seque bem a vaquinha","🌙 Dormir" to "Hora de descansar");val i=step.coerceIn(0,3);val c=base("🐮 CURRAL",s[i].second);val h=FrameLayout(this);cow3d=Cow3DView(this);h.addView(cow3d,FrameLayout.LayoutParams(-1,-1));c.addView(h,LinearLayout.LayoutParams(-1,520));c.addView(TextView(this).apply{text="${i+1}/4  ${s[i].first}";textSize=22f;gravity=Gravity.CENTER});c.addView(btn(s[i].first){if(i<3)showCare(i+1)else{stars+=5;hearts+=1;showCareDone()}},p());c.addView(btn("🏠 Voltar ao mapa"){showHome()},p());set(c)}
 private fun showCareDone(){val c=base("⭐ MUITO BEM!","Você cuidou da vaquinha!");c.addView(TextView(this).apply{text="+5 ⭐     +1 ❤️\n🐮💚";textSize=36f;gravity=Gravity.CENTER;setPadding(0,30,0,30)});c.addView(btn("🔁 Cuidar novamente"){showCare(0)},p());c.addView(btn("🏠 Voltar ao mapa"){showHome()},p());set(c)}
 private fun showFarm(step:Int){val s=listOf("💧 REGAR A HORTA" to "Regue as plantinhas","🌽 COLHER" to "A horta cresceu!","🥚 PEGAR OS OVOS" to "Visite o galinheiro");val i=step.coerceIn(0,2);val c=base(if(i==2)"🐔 GALINHEIRO" else "🌱 HORTA",s[i].second);c.addView(TextView(this).apply{text=when(i){0->"☀️   💧💧\n🌱 🌱 🌱 🌱\n🟫🟫🟫🟫";1->"☀️  🦋\n🌽 🥕 🍅 🌽\n🟫🟫🟫🟫";else->"🌳   🏡   🌳\n🐔   🐔\n🥚 🥚 🥚"};textSize=48f;gravity=Gravity.CENTER;setPadding(0,40,0,40)});c.addView(btn(s[i].first){if(i<2)showFarm(i+1)else{stars+=2;showReward()}},p());c.addView(btn("🏠 Voltar ao mapa"){showHome()},p());set(c)}
 private fun showReward(){val c=base("🎉 MUITO BEM!","Tarefa concluída — +2 estrelas!");c.addView(TextView(this).apply{text="⭐ ⭐\n🌻🐮🐔🌻";textSize=38f;gravity=Gravity.CENTER;setPadding(0,30,0,30)});c.addView(btn("🏠 Voltar ao mapa"){showHome()},p());set(c)}
 private fun showLake(){val c=base("🦆 LAGO","Área bônus desbloqueada!");c.addView(TextView(this).apply{text="☀️  🦋  ☁️\n🌳 🦆  🦆 🌳\n💧💧🐟💧💧\n🌿🌼🌿🌼🌿";textSize=44f;gravity=Gravity.CENTER;setPadding(0,35,0,35)});c.addView(TextView(this).apply{text="🐟 Toque para brincar com os peixinhos";textSize=18f;gravity=Gravity.CENTER;setPadding(0,8,0,18);setOnClickListener{Toast.makeText(this@MainActivity,"Splash! 🐟💦",Toast.LENGTH_SHORT).show()}},p());c.addView(btn("🏠 Voltar ao mapa"){showHome()},p());set(c)}
 private fun showLab(){val c=base("👕 ARMÁRIO","Tudo liberado para testar");val h=FrameLayout(this);stage2d=AnimalStageView(this).apply{visibility=View.GONE};cow3d=Cow3DView(this);h.addView(stage2d,FrameLayout.LayoutParams(-1,-1));h.addView(cow3d,FrameLayout.LayoutParams(-1,-1));c.addView(h,LinearLayout.LayoutParams(-1,500));status=TextView(this).apply{text="🐮 Vaca — arraste para girar";textSize=17f;gravity=Gravity.CENTER};c.addView(status);animals.forEach{(e,n,k)->c.addView(btn("$e $n  🔊"){selectedAnimal=k;selectedEmoji=e;val cow=k=="vaca";cow3d.visibility=if(cow)View.VISIBLE else View.GONE;stage2d.visibility=if(cow)View.GONE else View.VISIBLE;if(!cow){stage2d.setAnimal(e);stage2d.celebrate()};status.text="$e $n selecionado";soundPlayer.play(k)},p())};listOf("👒","🎀","🧢","👑","🕶️","🧣","🎩").forEach{a->c.addView(btn("🔓 $a Equipar"){if(selectedAnimal=="vaca")cow3d.setAccessory(a)else{stage2d.setAnimal(selectedEmoji," $a");stage2d.celebrate()}},p())};c.addView(btn("🏠 Voltar ao mapa"){showHome()},p());set(c)}
 override fun onDestroy(){soundPlayer.release();super.onDestroy()}
}
