package com.minhafazendinha.game

import android.graphics.drawable.GradientDrawable
import android.os.Bundle
import android.os.SystemClock
import android.view.Gravity
import android.view.View
import android.widget.*
import androidx.appcompat.app.AppCompatActivity

class MainActivity:AppCompatActivity(){
 private lateinit var soundPlayer:AnimalSoundPlayer;private lateinit var progress:GameProgress;private lateinit var stage2d:AnimalStageView;private lateinit var cow3d:Cow3DView;private lateinit var status:TextView
 private var selectedAnimal="vaca";private var selectedEmoji="🐮";private var selectedAccessory="";private var onHome=true
 private val animals get()=GameConfig.animals
 override fun onCreate(b:Bundle?){super.onCreate(b);progress=GameProgress(this);soundPlayer=AnimalSoundPlayer(this);showHome()}
 private fun round(color:Int,r:Float=28f,stroke:Int=0)=GradientDrawable().apply{setColor(color);cornerRadius=r;if(stroke!=0)setStroke(3,stroke)}
 private fun base(title:String,sub:String)=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;gravity=Gravity.CENTER_HORIZONTAL;setPadding(GameTheme.SCREEN_PADDING,GameTheme.SCREEN_PADDING,GameTheme.SCREEN_PADDING,32);background=GradientDrawable(GradientDrawable.Orientation.TOP_BOTTOM,GameTheme.backgroundColors());addView(TextView(this@MainActivity).apply{text="⭐ ${progress.stars}     ❤️ ${progress.hearts}";textSize=GameTheme.HUD_TEXT_SIZE;gravity=Gravity.END;setTextColor(GameTheme.hudText)});addView(TextView(this@MainActivity).apply{text=title;textSize=GameTheme.TITLE_TEXT_SIZE;gravity=Gravity.CENTER;setTextColor(GameTheme.titleText);setPadding(0,8,0,0)});addView(TextView(this@MainActivity).apply{text=sub;textSize=GameTheme.SUBTITLE_TEXT_SIZE;gravity=Gravity.CENTER;setTextColor(GameTheme.bodyText);setPadding(0,7,0,16)})}
 private fun pilotBase(title:String,sub:String)=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;gravity=Gravity.CENTER_HORIZONTAL;setPadding(GameTheme.SCREEN_PADDING,GameTheme.SCREEN_PADDING,GameTheme.SCREEN_PADDING,36);background=GradientDrawable(GradientDrawable.Orientation.TOP_BOTTOM,intArrayOf(VisualPilot.skyTop,VisualPilot.skyBottom));addView(TextView(this@MainActivity).apply{text="⭐ ${progress.stars}     ❤️ ${progress.hearts}";textSize=18f;gravity=Gravity.END;setTextColor(VisualPilot.ink);background=round(0xE6FFFFFF.toInt(),28f);setPadding(22,10,22,10)},p());addView(TextView(this@MainActivity).apply{text=title;textSize=31f;gravity=Gravity.CENTER;setTextColor(VisualPilot.ink);setPadding(0,12,0,0)});addView(TextView(this@MainActivity).apply{text=sub;textSize=18f;gravity=Gravity.CENTER;setTextColor(VisualPilot.ink);setPadding(0,5,0,15)})}
 private fun btn(t:String,click:()->Unit)=Button(this).apply{text=t;textSize=GameTheme.BUTTON_TEXT_SIZE;isAllCaps=false;minHeight=GameTheme.BUTTON_MIN_HEIGHT;setTextColor(GameTheme.primaryButtonText);backgroundTintList=null;background=round(GameTheme.primaryButton,GameTheme.BUTTON_RADIUS,GameTheme.primaryButtonBorder);elevation=GameTheme.BUTTON_ELEVATION;var lastTap=0L;setOnClickListener{val now=SystemClock.elapsedRealtime();if(now-lastTap>=GameTheme.TAP_DEBOUNCE_MS){lastTap=now;click()}}}
 private fun pilotBtn(t:String,click:()->Unit)=Button(this).apply{text=t;textSize=19f;isAllCaps=false;minHeight=64;setTextColor(VisualPilot.ink);backgroundTintList=null;background=round(VisualPilot.accent,30f,VisualPilot.woodDark);elevation=8f;var lastTap=0L;setOnClickListener{val now=SystemClock.elapsedRealtime();if(now-lastTap>=GameTheme.TAP_DEBOUNCE_MS){lastTap=now;click()}}}
 private fun p()=LinearLayout.LayoutParams(-1,-2).apply{setMargins(0,8,0,8)}
 private fun set(c:LinearLayout)=setContentView(ScrollView(this).apply{isFillViewport=true;setBackgroundColor(GameTheme.skyBottom);addView(c,android.view.ViewGroup.LayoutParams(-1,-1))})
 private fun homeBtn(c:LinearLayout)=c.addView(btn(GameConfig.HOME_LABEL){showHome()},p())
 private fun showHome(){onHome=true;soundPlayer.stop();val lake=progress.hasStars(GameConfig.LAKE_UNLOCK_STARS);val c=base(GameConfig.TITLE,GameConfig.SUBTITLE);c.addView(FarmSceneView(this),LinearLayout.LayoutParams(-1,430).apply{setMargins(0,4,0,16)});GameConfig.homeActions.forEach{item->c.addView(btn("${item.icon} ${item.title}"){when(item.id){"sounds"->showSounds();"care"->showCare(0);"farm"->showFarm(0,false);"coop"->showFarm(GameConfig.farmSteps.lastIndex,true);"wardrobe"->showLab()}},p())};c.addView(btn(if(lake)"🦆 LAGO — Liberado!" else "🔒 LAGO — Faltam ${(GameConfig.LAKE_UNLOCK_STARS-progress.stars).coerceAtLeast(0)} ⭐"){if(lake)showLake()else Toast.makeText(this,GameConfig.BONUS_LOCK_MESSAGE,Toast.LENGTH_SHORT).show()},p());set(c)}
 private fun showSounds(){onHome=false;soundPlayer.stop();var soundKey=animals.first().key;val first=animals.first();val c=base(GameConfig.SOUNDS_TITLE,GameConfig.SOUNDS_SUBTITLE);val name=TextView(this).apply{text=first.name.uppercase();textSize=25f;gravity=Gravity.CENTER;setTextColor(GameTheme.titleText)};val stage=AnimalStageView(this).apply{setSoundBoardMode(true);setAnimal(first.emoji);setOnClickListener{soundPlayer.playExtended(soundKey);celebrate()}};c.addView(stage,LinearLayout.LayoutParams(-1,390));c.addView(name,p());val grid=GridLayout(this).apply{columnCount=2};animals.forEach{a->grid.addView(btn("${a.emoji}  ${a.name}"){soundKey=a.key;name.text=a.name.uppercase();stage.setAnimal(a.emoji);stage.celebrate();soundPlayer.playExtended(a.key)},GridLayout.LayoutParams().apply{width=0;columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1f);setMargins(6,6,6,6)})};c.addView(grid);homeBtn(c);set(c)}
 private fun showCare(step:Int){onHome=false;soundPlayer.stop();val i=step.coerceIn(0,GameConfig.careSteps.lastIndex);val s=GameConfig.careSteps[i];val pilot=VisualPilot.appliesTo("cow_care");val c=if(pilot)pilotBase(VisualPilot.title,"${s.icon} ${s.instruction}")else base(GameConfig.CARE_TITLE,s.instruction);val production=if(pilot)MimosaProductionView(this).apply{setCareState(i)}else null;if(production!=null&&production.hasProductionAssets()){c.addView(production,LinearLayout.LayoutParams(-1,VisualPilot.sceneHeight).apply{setMargins(0,4,0,12)})}else{cow3d=Cow3DView(this).apply{setCareState(i);setPilotVisual(pilot)};c.addView(cow3d,LinearLayout.LayoutParams(-1,if(pilot)VisualPilot.sceneHeight else 520).apply{setMargins(0,4,0,12)})};c.addView(TextView(this).apply{text="${i+1}/${GameConfig.careSteps.size}  ${s.icon} ${s.title}\n${s.feedback}";textSize=if(pilot)20f else 21f;gravity=Gravity.CENTER;setTextColor(if(pilot)VisualPilot.ink else GameTheme.bodyText);setPadding(18,16,18,16);background=round(if(pilot)VisualPilot.cream else GameTheme.cardBackground,if(pilot)VisualPilot.cardRadius else GameTheme.CARD_RADIUS,if(pilot)VisualPilot.wood else GameTheme.cardBorder);elevation=if(pilot)7f else 0f},p());c.addView((if(pilot)pilotBtn("${s.icon}  ${s.title}"){soundPlayer.play("vaca");if(i<GameConfig.careSteps.lastIndex)showCare(i+1)else{progress.reward(GameConfig.CARE_STAR_REWARD,GameConfig.CARE_HEART_REWARD);showCareDone()}}else btn("${s.icon} ${s.title}"){soundPlayer.play("vaca");if(i<GameConfig.careSteps.lastIndex)showCare(i+1)else{progress.reward(GameConfig.CARE_STAR_REWARD,GameConfig.CARE_HEART_REWARD);showCareDone()}}),p());homeBtn(c);set(c)}
 private fun showCareDone(){onHome=false;val c=base(GameConfig.CARE_DONE_TITLE,GameConfig.CARE_DONE_SUBTITLE);c.addView(TextView(this).apply{text="+${GameConfig.CARE_STAR_REWARD} ⭐     +${GameConfig.CARE_HEART_REWARD} ❤️\n🐮💚";textSize=36f;gravity=Gravity.CENTER;setTextColor(GameTheme.titleText)});c.addView(btn("🔁 Cuidar novamente"){showCare(0)},p());homeBtn(c);set(c)}
 private fun showFarm(step:Int,directCoop:Boolean=false){onHome=false;soundPlayer.stop();val i=step.coerceIn(0,GameConfig.farmSteps.lastIndex);val s=GameConfig.farmSteps[i];val finish=i==GameConfig.farmSteps.lastIndex;val c=base(if(finish)GameConfig.COOP_TITLE else GameConfig.FARM_TITLE,"${i+1}. ${s.title}");val scene=GameSceneView(this).apply{setMode(s.scene)};c.addView(scene,LinearLayout.LayoutParams(-1,470));val progressText=TextView(this).apply{text="${s.progressIcon} 0/${s.taps}";textSize=23f;gravity=Gravity.CENTER;setTextColor(GameTheme.bodyText)};c.addView(progressText,p());var taps=0;lateinit var action:Button;action=btn("${s.icon} ${s.action}"){if(taps<s.taps){taps++;progressText.text="${s.progressIcon} $taps/${s.taps}";if(s.scene=="coop")soundPlayer.play("galinha");scene.animate().scaleX(1.025f).scaleY(1.025f).setDuration(100).withEndAction{scene.animate().scaleX(1f).scaleY(1f).duration=100};if(taps==s.taps){action.isEnabled=false;c.addView(btn(if(finish)"⭐ TERMINAR" else "➡️ PRÓXIMO"){if(!finish)showFarm(i+1,false)else{val reward=if(directCoop)GameConfig.COOP_REWARD else GameConfig.FARM_REWARD;progress.addStars(reward);showReward(reward)}},p())}}};c.addView(action,p());homeBtn(c);set(c)}
 private fun showReward(gained:Int){onHome=false;val c=base(GameConfig.REWARD_TITLE,"Você ganhou +$gained ⭐");c.addView(TextView(this).apply{text="${"⭐".repeat(gained)}\n🌽🥕🍅  🧺🥚\n🐔💛";textSize=38f;gravity=Gravity.CENTER;setTextColor(GameTheme.titleText)});c.addView(btn("🔁 Brincar novamente"){showFarm(0,false)},p());homeBtn(c);set(c)}
 private fun showLake(){onHome=false;soundPlayer.stop();val c=base(GameConfig.BONUS_TITLE,GameConfig.BONUS_SUBTITLE);val lake=GameSceneView(this).apply{setMode("lake");isClickable=true;setOnClickListener{animate().scaleX(1.03f).scaleY(1.03f).setDuration(120).withEndAction{animate().scaleX(1f).scaleY(1f).duration=120};Toast.makeText(this@MainActivity,"Splash! 🐟💦",Toast.LENGTH_SHORT).show()}};c.addView(lake,LinearLayout.LayoutParams(-1,680));c.addView(TextView(this).apply{text="👆 Toque no lago";textSize=18f;gravity=Gravity.CENTER;setTextColor(GameTheme.bodyText)},p());homeBtn(c);set(c)}
 private fun showLab(){onHome=false;soundPlayer.stop();selectedAccessory="";val c=base(GameConfig.WARDROBE_TITLE,GameConfig.WARDROBE_SUBTITLE);val h=FrameLayout(this).apply{background=round(GameTheme.wardrobeBackground,32f,GameTheme.cardBorder)};stage2d=AnimalStageView(this).apply{visibility=View.GONE};cow3d=Cow3DView(this);h.addView(stage2d,FrameLayout.LayoutParams(-1,-1));h.addView(cow3d,FrameLayout.LayoutParams(-1,-1));c.addView(h,LinearLayout.LayoutParams(-1,500));status=TextView(this).apply{text="🐮 Vaca — sem roupa";textSize=19f;gravity=Gravity.CENTER;setTextColor(GameTheme.bodyText)};c.addView(status);val animalGrid=GridLayout(this).apply{columnCount=2};animals.forEach{a->animalGrid.addView(btn("${a.emoji} ${a.name}"){selectedAnimal=a.key;selectedEmoji=a.emoji;selectedAccessory="";val cow=a.key=="vaca";cow3d.visibility=if(cow)View.VISIBLE else View.GONE;stage2d.visibility=if(cow)View.GONE else View.VISIBLE;cow3d.setAccessory("");if(!cow){stage2d.setAnimal(a.emoji);stage2d.celebrate()};status.text="${a.emoji} ${a.name} — sem roupa";soundPlayer.play(a.key)},GridLayout.LayoutParams().apply{width=0;columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1f)})};c.addView(animalGrid);c.addView(btn("🚫 SEM ROUPA"){selectedAccessory="";if(selectedAnimal=="vaca")cow3d.setAccessory("")else stage2d.setAnimal(selectedEmoji);status.text="$selectedEmoji Sem roupa"},p());val clothes=GridLayout(this).apply{columnCount=2};GameConfig.accessories.forEach{a->clothes.addView(btn("$a Equipar"){selectedAccessory=a;if(selectedAnimal=="vaca")cow3d.setAccessory(a)else{stage2d.setAnimal(selectedEmoji," $a");stage2d.celebrate()};status.text="$selectedEmoji Visual $a ✨"},GridLayout.LayoutParams().apply{width=0;columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1f)})};c.addView(clothes);c.addView(btn("📸 DESFILAR"){if(selectedAnimal=="vaca")cow3d.animate().scaleX(1.08f).scaleY(1.08f).setDuration(180).withEndAction{cow3d.animate().scaleX(1f).scaleY(1f).duration=180}else stage2d.celebrate();soundPlayer.play(selectedAnimal)},p());homeBtn(c);set(c)}
 @Deprecated("Deprecated in Java") override fun onBackPressed(){if(onHome)super.onBackPressed()else showHome()}
 override fun onDestroy(){soundPlayer.release();super.onDestroy()}
}